### ISSUE TITLE
client never reconnects

### ISSUE THREAD

**Issue by perrohunter** [nats-io/python-nats#15]
I'm hitting a bug where the NATS client never reconnects, im trying to publish something but if the connection reset for the first publish, the status of the connection wont reflect that, however after a second attemp the nc._status changes to 3 "RECONNECTING" and a call to `_unbind()` happens, there when the reconnection is happening this Task is never resuming, I assume because the IOLoop is stopped.

Inside `_schedule_primary_and_connect()` execution never passes beyond this snippet

```
      yield tornado.gen.Task(
        self._loop.add_timeout,
        timedelta(seconds=RECONNECT_TIME_WAIT))
```

The way I'm using `python-nats` is by storing the connection on a global for re-use, the calling my notify function as a `tornado.gen.coroutine`, this works fine until I reset NATS on purpose to check wether the connect is re-stablished.

```
def notify(who, what):
    try:
        tornado.ioloop.IOLoop.instance().run_sync(lambda: publish_notification(who=who, what=what))
    except Exception as e:
        print "DEBUG: Failed to notify: {}".format(e)
        traceback.print_exc()


@tornado.gen.coroutine
def publish_notification(who, what):
    if 'nats' not in GLOBAL_NATS:
        nc = NATS()
        GLOBAL_NATS['nats'] = nc
        # Establish connection to the server.
        options = {"verbose": True, "servers": ["nats://nats:4222"]}
        options['allow_reconnect'] = True
        yield nc.connect(**options)
    else:
        nc = GLOBAL_NATS['nats']
    yield nc.publish(who, what)
```

My theory is that the loop stops.

Steps to replicate:

1.- open nats connection
2.- publish something to see connection works
3.- reset nats (I run nats from the docker container)
4.- publish another message (nc._status == 1)
5.- publish another message (nc._status == 3)

**Comment by perrohunter** [comment]
as an additional note, if I comment out that delay block, the reconnect does happen

**Comment by wallyqs** [comment]
Hi @perrohunter :) Thanks for raising the issue and how to reproduce, I'll take a look...

**Comment by wallyqs** [comment]
Can you reproduce with a snippet as follows?  I think it might have give up reconnecting after a while in this case...

```python
import tornado.ioloop
import tornado.gen
from nats.io.client import Client as NATS

global nc
nc = None

@tornado.gen.coroutine
def publish_notification(who, what):
    global nc
    if nc is None:
        nc = NATS()
        options = {
            "servers": [
                "nats://127.0.0.1:4222"
                ]
            }
        yield nc.connect(**options)

    for i in range(10):
        yield nc.publish(who, what)
    yield tornado.gen.sleep(1)

if __name__ == '__main__':
    while True:
        tornado.ioloop.IOLoop.instance().run_sync(lambda: publish_notification(who="foo", what="bar"))
```

Also found that can't use option for infinite reconnects via `max_reconnect_attempts: -1` right now, so making an update to the client soon.

**Comment by perrohunter** [comment]
with this code, when `publish_notification` gets called after `nats` has been restarted, no message is delivered, however when a second attempt happen, 20 messages are delivered.

This shows that the first 10 messages were never lost, i can still see the reconnect attempt from the python nats client, but never passing past the same tornado task delay block. 

I also waited 120 seconds to see if a reconnect would happen.

as an additional note, the consumer of this published messages is using the `go-nats` client, but even after restart, I can see on `subz` the subscriptions being counted

**Comment by wallyqs** [comment]
Thanks for the update @perrohunter, I have a wip branch where I'm investigating this and along with adding infinite reconnect logic in case you want to give it a try: https://github.com/nats-io/python-nats/compare/max-reconnect-attempts

Example conf to always reconnect under that branch:
```python
 options = {
    "servers": [
       "nats://127.0.0.1:4222"
      ],
     "max_reconnect_attempts": -1,
     "reconnect_time_wait": 2
}
```
If you try that branch definitely let me know if you have any feedback, thanks! :)

**Comment by perrohunter** [comment]
hey @wallyqs this branch seems to definitively improve this scenario, I see the reconnect happen and successfully start publishing messages after a shortwhile, every publish however throws this exception even if it succeeds 

```
Traceback (most recent call last):
  File "/Users/perrohunter/esdev/django/temporal/chat/messages.py", line 60, in notify
    tornado.ioloop.IOLoop.instance().run_sync(lambda: publish_notification(who=who, what=what))
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/ioloop.py", line 444, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
TimeoutError: Operation timed out after None seconds
[01/Mar/2017 20:31:01] "POST /api/chat/v0.1/direct_channels/e8132f40-f9f3-11e6-8a56-f40f242e649d/rte/ HTTP/1.1" 200 9611
```

this is the code I used to test this branch

```

@tornado.gen.coroutine
def publish_notification(who, what):
    global nc
    if nc is None:
        nc = NATS()
        # Establish connection to the server.
        options = {
            "verbose": True,
            "servers": [
                "nats://" + settings.NATS_HOSTNAME + ":" + settings.NATS_PORT
            ],
            "max_reconnect_attempts": -1,
            "reconnect_time_wait": 2
        }

        yield nc.connect(**options)

    yield nc.publish(who, what)
    yield tornado.gen.sleep(1)
```

However if I restart nats yet again after this successful reconnect, this stack trace is thrown and a reconnect never happens again

```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x106a65f18>
Traceback (most recent call last):
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/ioloop.py", line 598, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/nats/io/client.py", line 700, in _unbind
    yield self._schedule_primary_and_connect()
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/nats/io/client.py", line 760, in _schedule_primary_and_connect
    yield self._server_connect(s)
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/nats/io/client.py", line 262, in _server_connect
    future)
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
TimeoutError: Timeout
Traceback (most recent call last):
  File "/Users/perrohunter/esdev/django/temporal/chat/messages.py", line 60, in notify
    tornado.ioloop.IOLoop.instance().run_sync(lambda: publish_notification(who=who, what=what))
  File "/Users/perrohunter/esdev/django/pyenv/lib/python2.7/site-packages/tornado/ioloop.py", line 444, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
TimeoutError: Operation timed out after None seconds
[01/Mar/2017 20:31:01] "POST /api/chat/v0.1/direct_channels/e8132f40-f9f3-11e6-8a56-f40f242e649d/rte/ HTTP/1.1" 200 9611

```

**Comment by wallyqs** [comment]
Hi, I made a release including the reconnect fixes for now, though haven't been able to reproduce this one with that error... I wonder if what is happening here could be related to the IO loop from tornado somehow, if so you could try setting explicitly which is the `io_loop` in the connect options too...
https://github.com/nats-io/python-nats/blob/master/examples/advanced-example.py#L11-L22


v0.5.0 --> https://pypi.python.org/pypi?:action=display&name=nats-client&version=0.5.0

**Comment by ColinSullivan1** [comment]
@perrohunter , just following up, have you encountered this issue with the latest release?

**Comment by perrohunter** [comment]
@ColinSullivan1 Hi Colin, I tried the the proposed version unsuccessfully, I ended up creating a small RPC service to nats
