### ISSUE TITLE
Connection fails if tls_required field missing from INFO block

### ISSUE THREAD

**Issue by ajoubertza** [nats-io/python-nats#46]
After installing v1.2.0 of [gnatsd](https://github.com/nats-io/gnatsd) (linux-amd64) the client connection fails with an exception.  Not sure if this is a defect in gnatsd, or if the client needs to be more lenient?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/my_package/my_module.py", line 123, in _setup_nats
    yield self.nats.connect(**nats_options)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/nats/io/client.py", line 240, in connect
    yield self._process_connect_init()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/nats/io/client.py", line 821, in _process_connect_init
    if self._server_info['tls_required']:
KeyError: 'tls_required'
```

gnatsd v1.1.0:  includes `tls_required` field in INFO
(and `auth_required` and `tls_verify`)
```
$ telnet localhost 4222
Trying 127.0.0.1...
Connected to localhost.localdomain.
Escape character is '^]'.
INFO {"server_id":"aBCDEtuGn9kb3qbAHGDD23","version":"1.1.0","git_commit":"","go":"go1.9.4","host":"0.0.0.0","port":4222,"auth_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576} 
```

gnatsd v1.2.0:  does not report `tls_required` field in INFO
```
$ telnet localhost 4222
Trying 127.0.0.1...
Connected to localhost.localdomain.
Escape character is '^]'.
INFO {"server_id":"tysypEmM3cABCDN06exi8e","version":"1.2.0","proto":1,"go":"go1.10.3","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":107} 
```

**Comment by wallyqs** [comment]
This is a bug in the client, updating with a fix today

**Comment by ajoubertza** [comment]
Thanks, @wallyqs.

**Comment by wallyqs** [comment]
Thanks for the report, I will make a hotfix release in a bit as well.

**Comment by ajoubertza** [comment]
Great - that was quick 👍

**Comment by wallyqs** [comment]
@ajoubertza np, new version should be available in pypi now https://pypi.org/project/nats-client/
Sorry for the inconvenience
