### ISSUE TITLE
Stream is closed

### ISSUE THREAD

**Issue by angeloramarolahy** [nats-io/python-nats#6]
Hi,

My use case :

- Message average size : 565Kb
- After each 10 messages sent, I call tornado.gen.sleep(0), so in the beginning it publish message 10 by 10. 
But, after a few publications, my application doesn't publish anymore and I get a StreamClosedError. 

I've the following stacktrace :

```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
  ret = callback()
File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
  return fn(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 615, in <lambda>
  self.add_future(ret, lambda f: f.result())
File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
  raise_exc_info(self._exc_info)
File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper

  yielded = next(result)
File "/usr/src/app/src/nats-client/nats/io/client.py", line 243, in _send_ping
  yield self.io.write(PING_PROTO)
File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 377, in write
  self._check_closed()
File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 885, in _check_closed
  raise StreamClosedError(real_error=self.error)
StreamClosedError: Stream is closed.
```

- After getting this error, my application publish the rest of the message, not 10 by 10 but all messages (with some lost messages).

I want to know if it is an issue according to a nats config, or something else...?

Regards,

**Comment by wallyqs** [comment]
Hi, thanks for sharing the issue, I will take a look. By the way, do you see any slow consumer errors in the nats server output?

**Comment by angeloramarolahy** [comment]
Hi, thanks for reply.
My consumer has no other error that this one inside my system.

**Comment by wallyqs** [comment]
Hi, I just pushed earlier some updates to the repo which would possibly address this. I will cut a release this week with the new changes too, feel free to reopen in case if you can reproduce.
